name: snakemake_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core
  - python=3.11
  - pip
  - snakemake=8.13.0
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - scikit-survival
  - lifelines
  - matplotlib
  - seaborn
  - plotly
  - pyyaml
  - mygene
  - reportlab
  - pdf2image
  - poppler
  - requests
  - tqdm
  - fastparquet
  - pyarrow

  # Extra utilities
  - yaml
  - ipykernel

  - pip:
      - transformers
      - torch
      - accelerate